#!/usr/bin/env bash

# This software is Copyright (c) 2021, Blackfell <github at blackfell.net>
# and it is hereby released to the general public under the following terms:

# Redistribution and use in source and binary forms, with or without
# modification, are permitted.

# Script Variables
MOUNT_POINT="/nas"
SUB_VOLUMES=("videos" "dump" "books" "games" "pictures" "public" "music" "syncthing" "emby" "backups" "tv" "movies")

# Configure Autosnapshotting Tools
echo "Getting btrfs-snp."
sudo wget https://raw.githubusercontent.com/blackfell/btrfs-snp/master/btrfs-snp -O /usr/local/sbin/btrfs-snp
sudo chmod +x /usr/local/sbin/btrfs-snp

# Get the disk name off the user
while true
do
	read -p "What is the full path of the disk you're using? (E.G. /dev/sda) : " DISK_NAME
	read -p "Working with $DISK_NAME, is that correct? [Y/n] " -n 1
	if [[ $REPLY  =~ ^[Yy]$ ]]
		then break
	fi
done

# Create a partition first please
echo "\nCreate a single partition now."
sudo fdisk $DISK_NAME
# Get the changes in teh kernel
sudo partprobe -s
echo "Disk should be visible"
ls -l /dev/ | grep sd
while true
do
	read -p "Enter the full path of the partition you're using? (E.G. /dev/sda1) : " DISK_PART
	read -p "Working with $DISK_PART, is that correct? [Y/n] " -n 1
	if [[ $REPLY  =~ ^[Yy]$ ]]
		then break
	fi
done

echo "Searching for UUID of our new volume"
PART_UUID=$(sudo blkid $DISK_PART | awk -F 'UUID=\"' '{print $2}' | cut -d '"' -f 1)
while true
do
	read -p "Got UUID of $PART_UUID for $disk_part. Is that correct? [y/N] " -n 1
	if [[ $REPLY  =~ ^[Yy]$ ]]
		then break
	fi
done


# Now configure BTRFS on it
echo "Creating BTRFS Volume"
sudo mkfs.btrfs -L ryiria $DISK_PART
echo "Creating mount point at $MOUNT_POINT"
sudo mkdir -v -p $MOUNT_POINT
sudo mount $DISK_PART $MOUNT_POINT
echo "Status:"
df -h $MOUNT_POINT

echo "Creating Subvolumes & configuring snapshots"
sudo btrfs subvolume create $MOUNT_POINT/.snapshots
echo -e "#!/usr/bin/env bash\n" | sudo tee /etc/cron.hourly/btrfs-snp
for s in "${SUB_VOLUMES[@]}"
do
	echo "creating $MOUNT_POINT/$s"
	sudo btrfs subvolume create $MOUNT_POINT/$s
	echo "FSTAB entry:"
	echo -e "UUID=$PART_UUID\t$MOUNT_POINT/$s\tbtrfs\tsubvol=$s\t0\t0" | sudo tee -a /etc/fstab
	
	BTRFS_SCRIPT="
	/usr/local/sbin/btrfs-snp $MOUNT_POINT/$s bi-hourly-$s   4 7200    $MOUNT_POINT/.snapshots\n
	/usr/local/sbin/btrfs-snp $MOUNT_POINT/$s daily-$s       4 86400   $MOUNT_POINT/.snapshots\n
	/usr/local/sbin/btrfs-snp $MOUNT_POINT/$s weekly-$s      8 604800  $MOUNT_POINT/.snapshots\n
	/usr/local/sbin/btrfs-snp $MOUNT_POINT/$s tri-monthly-$s 4 7889400 $MOUNT_POINT/.snapshots\n
	"
	echo "Configuring Snapshots for $s."
	echo -e $BTRFS_SCRIPT | sudo tee -a /etc/cron.hourly/btrfs-snp >/dev/null
done

echo "FSTAB entries: "
cat /etc/fstab

echo "Cron jobs are:"
sudo chmod +x /etc/cron.hourly/btrfs-snp
cat /etc/cron.hourly/btrfs-snp

echo "THERE YOU GO:"
sudo btrfs filesystem show
sudo btrfs filesystem usage $MOUNT_POINT
